const elements = {
  FE_BLEND: "feBlend",
  FE_COLOR_MATRIX: "feColorMatrix",
  FE_COMPONENT_TRANSFER: "feComponentTransfer",
  FE_COMPOSITE: "feComposite",
  FE_CONVOLVE_MATRIX: "feConvolveMatrix",
  FE_DIFFUSE_LIGHTING: "feDiffuseLighting",
  FE_DISPLACEMENT_MAP: "feDisplacementMap",
  FE_DROP_SHADOW: "feDropShadow",
  FE_FLOOD: "feFlood",
  FE_FUNC_A: "feFuncA",
  FE_FUNC_B: "feFuncB",
  FE_FUNC_G: "feFuncG",
  FE_FUNC_R: "feFuncR",
  FE_GAUSSIAN_BLUR: "feGaussianBlur",
  FE_IMAGE: "feImage",
  FE_MERGE: "feMerge",
  FE_MERGE_NODE: "feMergeNode",
  FE_MORPHOLOGY: "feMorphology",
  FE_OFFSET: "feOffset",
  FE_SPECULAR_LIGHTING: "feSpecularLighting",
  FE_TILE: "feTile",
  FE_TURBULENCE: "feTurbulence",
};

const attributes = {
  AMPLITUDE: "amplitude",
  BASE_FREQUENCY: "baseFrequency",
  BIAS: "bias",
  DIFFUSE_CONSTANT: "diffuseConstant",
  DIVISOR: "divisor",
  DX: "dx",
  DY: "dy",
  EDGE_MODE: "edgeMode",
  EXPONENT: "exponent",
  FLOOD_COLOR: "floodColor",
  FLOOD_OPACITY: "floodOpacity",
  HEIGHT: "height",
  IN: "in",
  IN2: "in2",
  INTERCEPT: "intercept",
  K1: "k1",
  K2: "k2",
  K3: "k3",
  K4: "k4",
  KERNEL_MATRIX: "kernelMatrix",
  KERNEL_UNIT_LENGTH: "kernelUnitLength",
  MODE: "mode",
  NUM_OCTAVES: "numOctaves",
  OFFSET: "offset",
  OPERATOR: "operator",
  ORDER: "order",
  PRESERVE_ALPHA: "preserveAlpha",
  PRESERVE_ASPECT_RATIO: "preserveAspectRatio",
  RADIUS: "radius",
  RESULT: "result",
  SCALE: "scale",
  SEED: "seed",
  SLOPE: "slope",
  SPECULAR_CONSTANT: "specularConstant",
  SPECULAR_EXPONENT: "specularExponent",
  STD_DEVIATION: "stdDeviation",
  STITCH_TILES: "stitchTiles",
  SURFACE_SCALE: "surfaceScale",
  TABLE_VALUES: "tableValues",
  TARGET_X: "targetX",
  TARGET_Y: "targetY",
  TYPE: "type",
  VALUES: "values",
  WIDTH: "width",
  X_CHANNEL_SELECTOR: "xChannelSelector",
  X: "x",
  XLINK_HREF: "xlinkHref",
  Y_CHANNEL_SELECTOR: "yChannelSelector",
  Y: "y",
};

const sharedAttributes = [
  attributes.HEIGHT,
  attributes.RESULT,
  attributes.WIDTH,
  attributes.X,
  attributes.Y,
];

const transferFunctionAttributes = [
  attributes.AMPLITUDE,
  attributes.EXPONENT,
  attributes.INTERCEPT,
  attributes.OFFSET,
  attributes.SLOPE,
  attributes.TABLE_VALUES,
  attributes.TYPE,
];

const attributesByElement = {
  [elements.FE_BLEND]: [
    ...sharedAttributes,
    attributes.IN,
    attributes.IN2,
    attributes.MODE,
  ],
  [elements.FE_COLOR_MATRIX]: [
    ...sharedAttributes,
    attributes.IN,
    attributes.TYPE,
    attributes.VALUES,
  ],
  [elements.FE_COMPONENT_TRANSFER]: [...sharedAttributes, attributes.IN],
  [elements.FE_COMPOSITE]: [
    ...sharedAttributes,
    attributes.IN,
    attributes.IN2,
    attributes.K1,
    attributes.K2,
    attributes.K3,
    attributes.K4,
    attributes.OPERATOR,
  ],
  [elements.FE_CONVOLVE_MATRIX]: [
    ...sharedAttributes,
    attributes.BIAS,
    attributes.DIVISOR,
    attributes.EDGE_MODE,
    attributes.IN,
    attributes.KERNEL_MATRIX,
    attributes.KERNEL_UNIT_LENGTH,
    attributes.ORDER,
    attributes.PRESERVE_ALPHA,
    attributes.TARGET_X,
    attributes.TARGET_Y,
  ],
  [elements.FE_DIFFUSE_LIGHTING]: [
    ...sharedAttributes,
    attributes.DIFFUSE_CONSTANT,
    attributes.IN,
    attributes.KERNEL_UNIT_LENGTH,
    attributes.SURFACE_SCALE,
  ],
  [elements.FE_DISPLACEMENT_MAP]: [
    ...sharedAttributes,
    attributes.IN,
    attributes.IN2,
    attributes.SCALE,
    attributes.X_CHANNEL_SELECTOR,
    attributes.Y_CHANNEL_SELECTOR,
  ],
  [elements.FE_DROP_SHADOW]: [
    ...sharedAttributes,
    attributes.DX,
    attributes.DY,
    attributes.STD_DEVIATION,
  ],
  [elements.FE_FLOOD]: [
    ...sharedAttributes,
    attributes.FLOOD_COLOR,
    attributes.FLOOD_OPACITY,
  ],
  [elements.FE_FUNC_A]: [...transferFunctionAttributes],
  [elements.FE_FUNC_B]: [...transferFunctionAttributes],
  [elements.FE_FUNC_G]: [...transferFunctionAttributes],
  [elements.FE_FUNC_R]: [...transferFunctionAttributes],
  [elements.FE_GAUSSIAN_BLUR]: [
    ...sharedAttributes,
    attributes.EDGE_MODE,
    attributes.IN,
    attributes.STD_DEVIATION,
  ],
  [elements.FE_IMAGE]: [
    ...sharedAttributes,
    attributes.PRESERVE_ASPECT_RATIO,
    attributes.XLINK_HREF,
  ],
  [elements.FE_MERGE]: [...sharedAttributes],
  [elements.FE_MERGE_NODE]: [attributes.IN],
  [elements.FE_MORPHOLOGY]: [
    ...sharedAttributes,
    attributes.IN,
    attributes.OPERATOR,
    attributes.RADIUS,
  ],
  [elements.FE_OFFSET]: [
    ...sharedAttributes,
    attributes.IN,
    attributes.DX,
    attributes.DY,
  ],
  [elements.FE_SPECULAR_LIGHTING]: [
    ...sharedAttributes,
    attributes.IN,
    attributes.KERNEL_UNIT_LENGTH,
    attributes.SPECULAR_CONSTANT,
    attributes.SPECULAR_EXPONENT,
    attributes.SURFACE_SCALE,
  ],
  [elements.FE_TILE]: [...sharedAttributes, attributes.IN],
  [elements.FE_TURBULENCE]: [
    ...sharedAttributes,
    attributes.BASE_FREQUENCY,
    attributes.NUM_OCTAVES,
    attributes.SEED,
    attributes.STITCH_TILES,
    attributes.TYPE,
  ],
};

export const FILTER_PRIMITIVES = Object.values(elements);

export const FILTER_PRIMITIVE_ATTRIBUTE_MAP = attributesByElement;

export const COMMON_FILTER_PRIMITIVE_ATTRIBUTES = sharedAttributes;
